sudo: required

language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: stable
        - rust: beta

cache: cargo

env:
    - KEYBASE_USER=passbase_test

install:
    - cargo build

before_script:
    - mv target/debug/passbase test/bin

script:
    - ./test/tests.sh
